language: python
python:
  - "3.4"
script:
  - python -m json.tool < movies.json
after_success:
  - mkdir deploy
  - cp movies.json deploy/
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: alfred-dev-data
  region: $AWS_REGION
  skip_cleanup: true
  upload-dir: ./
  local_dir: deploy